apiVersion: v1
description: acs-aks-migrate sample app
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
name: acs-aks-migrate-sample
version: 1.0.0
appVersion: 1.0.0
sources:
- https://github.com/ritazh/acs-aks-migrate
maintainers:
- name: ritazh
  email: ritazh@microsoft.com